# This is a basic workflow to help you get started with Actions

name: Schedule

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  schedule:
    - cron: '11 11 * * 1,3,5'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Print:
    # The type of runner that the job
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will 
    steps:
      - name: Scheduling for monday, wednesday, friday
        run: echo "it's 11:00 pm"
        shell: bash
